### ISSUE TITLE
There are 2000+ tweets in the test dataset of MediaEval 2016. But only around 600 tweets have relative pictures in it

### ISSUE THREAD

**Issue by xiaolan98** [MKLab-ITI/image-verification-corpus#2]
Are there other pictures of the test dataset of MediaEval 2016?

**Comment by xiaolan98** [comment]
Paper Verifying Multimedia Use at MediaEval 2016 says that there are 104 cases of real and misused
images and 25 cases of real and misused videos, in total associated with 1,107 and 1,121 posts, respectively, but why only 64 pictures lie in MediaEval 2016?

**Comment by olgapapa** [comment]
We updated the zip file in https://github.com/MKLab-ITI/image-verification-corpus/tree/master/mediaeval2016/testset with the missing images and text files. Each text file contains a URL of the video that the corresponding tweet shares. For example, the tweet with id '651118294447951872' (in posts.txt) shares the video with URL stored in 'airstrikes_1.txt'. All tweets have either an image or a video.

**Comment by xiaolan98** [comment]
thank you very much
